### ISSUE TITLE
Extra ȼ๏๏ℓness features needed

### ISSUE THREAD

**Issue by runofthemillgeek** [shubhodeep9/kEwL.js#1]
Like stuff from https://coolsymbol.com/cool-fancy-text-generator.html

These were gold during Orkut days. 😂

Eg: ɨ ąʍ ȼ๏๏ℓ

P.S. Does any package exist in npm for this? 🤔

**Comment by shubhodeep9** [comment]
@sangeeth96 it should now.
Let's make it kewler
can you work on it?

**Comment by runofthemillgeek** [comment]
I am occupied for like 2 days but I'd love to. Not sure how to approach this though because I don't have much understanding of Unicode and how to go about this. We could just copy paste the string of characters and map it 1-1 to alphabets + digits but would that be right? Any thoughts? Also, the dir structure has to converted to a lib format.

**Comment by shubhodeep9** [comment]
@sangeeth96 I too think map will be the best approach. 
Let's give developers the option to choose via the html attribute `kewl="<option>"`
Where options are:
- altercase
- bubble
- Paranormal
- and so on

**Comment by shubhodeep9** [comment]
On the matter of structure,
I will make a library structure, and everything will compile and minify to a folder named `dist` where the final files will reside.
